# Generated by Django 5.1.7 on 2025-03-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_balance', models.FloatField()),
                ('fee_statement', models.FloatField()),
                ('fee_structure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BIT 111', 'BIT 111'), ('BIT 117', 'BIT 117'), ('BIT 210', 'BIT 211'), ('BIT 213', 'BIT 227'), ('BIT 313', 'BIT 310'), ('BIT 311', 'BIT 322'), ('BIT 410', 'BIT 411'), ('BIT 423', 'BIT 424')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')])),
                ('result_session', models.IntegerField()),
                ('result_grade', models.CharField(max_length=2)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SupplementaryExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_session', models.IntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_session', models.IntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Retake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.unit')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.year'),
        ),
    ]
