# Generated by Django 5.1.7 on 2025-04-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='unit',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='year',
            name='year_number',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')]),
        ),
    ]
