# Generated by Django 5.1.7 on 2025-04-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0009_alter_transcript_result_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialexam',
            unique_together={('unit', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='supplementaryexam',
            unique_together={('unit', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('code', 'student', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('code', 'year')},
        ),
    ]
