# Generated by Django 5.1.7 on 2025-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0010_alter_specialexam_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
