# Generated by Django 5.1.7 on 2025-04-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0011_clearancerequest_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearancerequest',
            old_name='approved',
            new_name='approve',
        ),
    ]
