# Generated by Django 5.1.7 on 2025-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0012_rename_approved_clearancerequest_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default_email@example.com', max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Retake',
        ),
    ]
