# Generated by Django 5.1.7 on 2025-04-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0013_student_email_delete_retake'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Academic.student'),
        ),
    ]
